{% set name = "oras" %}
{% set version = "0.14.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/oras-project/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 112b3c9eeb6a84894c42f2f40490c7364bf45c8f7cbd10fec7b792805ed96eed

build:
  number: 0
  script:
    - mkdir -p $PREFIX/bin                                 # [unix]
    - make build-mac                                       # [osx and not aarch64]
    - mv bin/darwin/amd64/oras $PREFIX/bin/oras            # [osx and not aarch64]
    - make build-linux                                     # [linux and x86_64]
    - mv bin/linux/amd64/oras $PREFIX/bin/oras             # [linux and x86_64]
    # Make sure a binary has been installed for all unix platforms
    - which oras  # [unix]
    - setlocal enableextensions       # [win]
    - mkdir -p %PREFIX%\Library\bin   # [win]
    - make build-windows                                   # [win]
    - move bin\windows\amd64\oras.exe %PREFIX%\Library\bin\oras.exe   # [win]
    - bash $RECIPE_DIR/collect_licenses.sh  # [unix]
    - bash %RECIPE_DIR%\\collect_licenses.sh  # [win]

    # - make build-mac-arm64
    # - mv bin/darwin/arm64/oras $PREFIX/bin/oras

requirements:
  build:
    - {{ compiler("go") }}
    - make  # [not win]
    - m2-make  # [win]
    - go-licenses

test:
  commands:
    - oras --help

about:
  home: https://github.com/oras-project/oras
  doc_url: https://oras.land/
  license: Apache-2.0
  license_file:
    - LICENSE
    - library_licenses/

  summary: ORAS project provides a way to push and pull OCI Artifacts to and from OCI Registries.

extra:
  recipe-maintainers:
    - wolfv
